title: Samuel M. Ortil
description: Software Engineer | Full Stack Developer | JavaScript | Typescript | ReactJS (Vite) | NodeJS (ExpressJS | NestJS) | DB (MongoDB | Postgresql) | CMS (WordPress & Wix) | Java
